#ifndef UHCI_STORAGE_STATS_H
#define UHCI_STORAGE_STATS_H

#define UHCI_STORAGE_STATS_PARAMETER "UHCIStorageStats"
#define UHCI_STORAGE_PROFILE_PARAMETER "UHCIStorageProfile"
#define UHCI_IMOD_PARAMETER "UHCIInterruptModerationUS"
#define UHCI_STORAGE_STATS_VERSION 1
/* Ten 32-bit header words followed by low/high pairs of 64-bit metrics. */
#define UHCI_STORAGE_STATS_HEADER 10
enum {
    UHCI_STAT_READS, UHCI_STAT_BYTES, UHCI_STAT_ERRORS,
    UHCI_STAT_REQUEST_NS, UHCI_STAT_LOCK_NS, UHCI_STAT_MAP_NS,
    UHCI_STAT_CLIENT_COPY_NS, UHCI_STAT_UNMAP_NS,
    UHCI_STAT_STAGE_BASE
};
enum {
    UHCI_STAGE_COUNT, UHCI_STAGE_ERRORS, UHCI_STAGE_PREPARE_NS,
    UHCI_STAGE_SERVICE_NS, UHCI_STAGE_RESUME_NS, UHCI_STAGE_COPY_NS,
    UHCI_STAGE_TOTAL_NS, UHCI_STAGE_METRICS
};
enum { UHCI_STAGE_CBW, UHCI_STAGE_DATA, UHCI_STAGE_CSW, UHCI_STAGE_CONTROL,
       UHCI_STAGE_TYPES };
#define UHCI_STORAGE_METRICS (UHCI_STAT_STAGE_BASE + UHCI_STAGE_TYPES * UHCI_STAGE_METRICS)
#define UHCI_STORAGE_STATS_WORDS (UHCI_STORAGE_STATS_HEADER + 2 * UHCI_STORAGE_METRICS)

#endif
